### ISSUE TITLE
yolov4-tiny convert failed

### ISSUE THREAD

**Issue by Softwaring** [ChenYingpeng/darknet2caffe#18]
Thanks for your help.

```
unknow layer type yolo
Traceback (most recent call last):
  File "darknet2caffe.py", line 519, in <module>
    darknet2caffe(cfgfile, weightfile, protofile, caffemodel)
  File "darknet2caffe.py", line 61, in darknet2caffe
    start = load_conv_bn2caffe(buf, start, params[conv_layer_name], params[bn_layer_name], params[scale_layer_name])
  File "darknet2caffe.py", line 150, in load_conv_bn2caffe
    conv_param[0].data[...] = np.reshape(buf[start:start+conv_weight.size], conv_weight.shape); start = start + conv_weight.size
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 257, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 52, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: cannot reshape array of size 695826 into shape (256,384,3,3)
```
[yolov4-tiny.cfg](https://github.com/ChenYingpeng/darknet2caffe/files/4958551/yolov4-tiny.cfg.txt)

**Comment by xs-trinity-lwei** [comment]
I have the same problem as you，It seems that ‘weights buf’ is not enough to convert.

**Comment by ChenYingpeng** [comment]
Please care route layer in yolov4-tiny.cfg. 
`[route]
layers=-1
groups=2
group_id=1`
It change this layer output_size = input_size / groups, you should change concate layer in caffe.

**Comment by ChenYingpeng** [comment]
> Thanks for your help.
> 
> ```
> unknow layer type yolo
> Traceback (most recent call last):
>   File "darknet2caffe.py", line 519, in <module>
>     darknet2caffe(cfgfile, weightfile, protofile, caffemodel)
>   File "darknet2caffe.py", line 61, in darknet2caffe
>     start = load_conv_bn2caffe(buf, start, params[conv_layer_name], params[bn_layer_name], params[scale_layer_name])
>   File "darknet2caffe.py", line 150, in load_conv_bn2caffe
>     conv_param[0].data[...] = np.reshape(buf[start:start+conv_weight.size], conv_weight.shape); start = start + conv_weight.size
>   File "/usr/local/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 257, in reshape
>     return _wrapfunc(a, 'reshape', newshape, order=order)
>   File "/usr/local/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 52, in _wrapfunc
>     return getattr(obj, method)(*args, **kwds)
> ValueError: cannot reshape array of size 695826 into shape (256,384,3,3)
> ```
> 
> [yolov4-tiny.cfg](https://github.com/ChenYingpeng/darknet2caffe/files/4958551/yolov4-tiny.cfg.txt)

Hi, Softwaring
[route]
layers=-1
groups=2
group_id=1
This layer output_size = input_size / groups, you should change concate layer in caffe.

**Comment by xs-trinity-lwei** [comment]
The yolov4（not tiny） has the same ‘route’ layer.Although the current tool can successfully convert yolov4 to caffe,Will there be some problems.

**Comment by Softwaring** [comment]
@ChenYingpeng  Thanks for your reply!

**Comment by hp-93** [comment]
so，I want to know how to solve this problem(groups and group_id)

**Comment by lesterlee89** [comment]
@Softwaring @ChenYingpeng is there some tips to convert caffe without change the layers,thanks

**Comment by Chalay** [comment]
> > Thanks for your help.
> > ```
> > unknow layer type yolo
> > Traceback (most recent call last):
> >   File "darknet2caffe.py", line 519, in <module>
> >     darknet2caffe(cfgfile, weightfile, protofile, caffemodel)
> >   File "darknet2caffe.py", line 61, in darknet2caffe
> >     start = load_conv_bn2caffe(buf, start, params[conv_layer_name], params[bn_layer_name], params[scale_layer_name])
> >   File "darknet2caffe.py", line 150, in load_conv_bn2caffe
> >     conv_param[0].data[...] = np.reshape(buf[start:start+conv_weight.size], conv_weight.shape); start = start + conv_weight.size
> >   File "/usr/local/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 257, in reshape
> >     return _wrapfunc(a, 'reshape', newshape, order=order)
> >   File "/usr/local/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 52, in _wrapfunc
> >     return getattr(obj, method)(*args, **kwds)
> > ValueError: cannot reshape array of size 695826 into shape (256,384,3,3)
> > ```
> > 
> > 
> > [yolov4-tiny.cfg](https://github.com/ChenYingpeng/darknet2caffe/files/4958551/yolov4-tiny.cfg.txt)
> 
> Hi, Softwaring
> [route]
> layers=-1
> groups=2
> group_id=1
> This layer output_size = input_size / groups, you should change concate layer in caffe.

Hi,ChenYingpeng
As well know, concate layer in caffe did not have parameter like dropout 50% to select the group id to the output, chould you point out how to motify the concate layer?   I had train a networking and facing the same problem， now I delect the "groups" and "groups_id" parameter to sucessfully convert the model to caffemodel format.  

Hoping Ur reply @.@

**Comment by jerryho-quanta** [comment]
Hello,
@ChenYingpeng 
@Softwaring 

I also meet ths same problem,

Traceback (most recent call last):
  File "darknet2caffe.py", line 569, in <module>
    darknet2caffe(cfgfile, weightfile, protofile, caffemodel)
  File "darknet2caffe.py", line 65, in darknet2caffe
    start = load_conv_bn2caffe(buf, start, params[conv_layer_name], params[bn_layer_name], params[scale_layer_name],conv_layer_name)
  File "darknet2caffe.py", line 184, in load_conv_bn2caffe
    conv_param[0].data[...] = np.reshape(buf[start:start+conv_weight.size], conv_weight.shape); start = start + conv_weight.size
  File "<__array_function__ internals>", line 6, in reshape
  File "/home/jerry/.local/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 301, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/home/jerry/.local/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 61, in _wrapfunc
    return bound(*args, **kwds)
ValueError: cannot reshape array of size 756735 into shape (256,384,3,3)

Could you share how to fix this problem?

Thanks,
