### ISSUE TITLE
YOLOv3 conversion failed

### ISSUE THREAD

**Issue by dsgh2** [ChenYingpeng/darknet2caffe#19]
Hi,
I have a problem converting YOLOv3.

in darknet2caffe.py, Line20,
    net = caffe.Net(protofile, caffe.TEST)

net has not any values(=empty)

It seems to be worked like below

<_io.TextIOWrapper name='result\\yolov3.prototxt' mode='w' encoding='cp949'> layer {
<_io.TextIOWrapper name='result\\yolov3.prototxt' mode='w' encoding='cp949'>     bottom: "layer105-conv"
<_io.TextIOWrapper name='result\\yolov3.prototxt' mode='w' encoding='cp949'>     top: "layer106-conv"
<_io.TextIOWrapper name='result\\yolov3.prototxt' mode='w' encoding='cp949'>     name: "layer106-conv"
<_io.TextIOWrapper name='result\\yolov3.prototxt' mode='w' encoding='cp949'>     type: "Convolution"
<_io.TextIOWrapper name='result\\yolov3.prototxt' mode='w' encoding='cp949'>     convolution_param {
<_io.TextIOWrapper name='result\\yolov3.prototxt' mode='w' encoding='cp949'>         num_output: 18
<_io.TextIOWrapper name='result\\yolov3.prototxt' mode='w' encoding='cp949'>         kernel_size: 1
<_io.TextIOWrapper name='result\\yolov3.prototxt' mode='w' encoding='cp949'>         pad: 0
<_io.TextIOWrapper name='result\\yolov3.prototxt' mode='w' encoding='cp949'>         stride: 1
<_io.TextIOWrapper name='result\\yolov3.prototxt' mode='w' encoding='cp949'>         bias_term: true
<_io.TextIOWrapper name='result\\yolov3.prototxt' mode='w' encoding='cp949'>     }
<_io.TextIOWrapper name='result\\yolov3.prototxt' mode='w' encoding='cp949'> }

however, it says

I0724 00:32:51.248684  5636 net.cpp:255] Network initialization done.
Traceback (most recent call last):
  File "darknet2caffe.py", line 522, in <module>
    darknet2caffe(cfgfile, weightfile, protofile, caffemodel)
  File "darknet2caffe.py", line 64, in darknet2caffe
    start = load_conv_bn2caffe(buf, start, params[conv_layer_name], params[bn_layer_name], params[scale_layer_name])
KeyError: 'layer1-conv'

How can I fix this?
Thanks in advance

**Comment by sakethkhandavalli** [comment]
I0825 16:14:20.889731 26193 layer_factory.hpp:77] Creating layer input
I0825 16:14:20.889760 26193 net.cpp:86] Creating Layer input
I0825 16:14:20.889766 26193 net.cpp:382] input -> data
I0825 16:14:20.889814 26193 net.cpp:124] Setting up input
I0825 16:14:20.889819 26193 net.cpp:131] Top shape: 1 3 320 320 (307200)
I0825 16:14:20.889824 26193 net.cpp:139] Memory required for data: 1228800
I0825 16:14:20.889827 26193 net.cpp:202] input does not need backward computation.
I0825 16:14:20.889830 26193 net.cpp:244] This network produces output data
I0825 16:14:20.889833 26193 net.cpp:257] Network initialization done.
Traceback (most recent call last):
  File "darknet2caffe.py", line 519, in <module>
    darknet2caffe(cfgfile, weightfile, protofile, caffemodel)
  File "darknet2caffe.py", line 61, in darknet2caffe
    start = load_conv_bn2caffe(buf, start, params[conv_layer_name], params[bn_layer_name], params[scale_layer_name])
KeyError: 'layer1-conv'

I am getting a similar error too, 'layer1-conv' key is missing, can anyone please tell me how to fix it. I am trying to convert a yolo-v3 model to caffe.
@ChenYingpeng @becauseofAI @dsgh2

**Comment by KelvinHuang666** [comment]
i got the same bug when i changing darknet yolov2 model to caffe,how can I solve it,thanks.

**Comment by yousong1992** [comment]
same error KeyError:'layer1-conv' is missing

**Comment by yousong1992** [comment]
@sakethkhandavalli @ChenYingpeng  plz help

**Comment by ChenYingpeng** [comment]
@yousong1992 @KelvinHuang666 @dsgh2 @sakethkhandavalli pls see this [link](https://github.com/ChenYingpeng/caffe-yolov3/issues/28).

**Comment by dsgh2** [comment]
Thank you!
