### ISSUE TITLE
caffe.proto:1455:1: Expected "required", "optional", or "repeated".

### ISSUE THREAD

**Issue by futureflsl** [ChenYingpeng/darknet2caffe#22]
when I Add below code into src/caffe/proto/caffe.proto.
// LayerParameter next available layer-specific ID: 147 (last added: recurrent_param)
message LayerParameter {
  optional TileParameter tile_param = 138;
  optional VideoDataParameter video_data_param = 207;
  optional WindowDataParameter window_data_param = 129;
++optional UpsampleParameter upsample_param = 149; //added by chen for Yolov3, make sure this id 149 not the same as before.
++optional MishParameter mish_param = 150; //added by chen for yolov4,make sure this id 150 not the same as before.
}

// added by chen for YoloV3
++message UpsampleParameter{
++  optional int32 scale = 1 [default = 1];
++}

// Message that stores parameters used by MishLayer
++message MishParameter {
++  enum Engine {
++    DEFAULT = 0;
++    CAFFE = 1;
++    CUDNN = 2;
++  }
++  optional Engine engine = 2 [default = DEFAULT];
++}

then remake caffe,error occurred
caffe.proto:1455:1: Expected "required", "optional", or "repeated".
caffe.proto:1455:1: Expected type name.
caffe.proto:1456:1: Expected "required", "optional", or "repeated".
caffe.proto:1456:1: Expected type name.
caffe.proto:1460:1: Expected top-level statement (e.g. "message").
caffe.proto:1465:1: Expected top-level statement (e.g. "message").
NVCC src/caffe/layers/relu_layer.cu
NVCC src/caffe/layers/exp_layer.cu
Makefile:648: recipe for target '.build_release/src/caffe/proto/caffe.pb.cc' failed
make: *** [.build_release/src/caffe/proto/caffe.pb.cc] Error 1
make: *** Waiting for unfinished jobs....

**Comment by futureflsl** [comment]
++ represent add line to proto,now it work well

**Comment by pranav7066** [comment]
How to remove the error? I am getting it too. Should I remove the ++?
