### ISSUE TITLE
深度可分离卷积ConvolutionDepthwise的hpp、cpp、cu和caffe.proto文件

### ISSUE THREAD

**Issue by lzh420202** [ChenYingpeng/darknet2caffe#25]
我想转换cfg样例中的mobilenet_v1_yolov3.cfg模型，不清楚你是用的哪种实现，能不能发一份资源连接，谢谢。

**Comment by ChenYingpeng** [comment]
Please see this [link](https://github.com/BVLC/caffe/pull/5665/files)

**Comment by lzh420202** [comment]
> Please see this [link](https://github.com/BVLC/caffe/pull/5665/files)

谢谢你的回复，我看了这个caffe实现，请问怎么在pjreddie/darknet中添加并支持对应的深度可分离卷积层来进行训练呢？

**Comment by ChenYingpeng** [comment]
https://github.com/ChenYingpeng/darknet-mobilenet

**Comment by lzh420202** [comment]
> https://github.com/ChenYingpeng/darknet-mobilenet

真的非常感谢。您的工作对我的帮助非常大，谢谢。
