### ISSUE TITLE
unknow layer type yolo 

### ISSUE THREAD

**Issue by imzongjian** [ChenYingpeng/darknet2caffe#6]
python darknet2caffe.py  cfg/yolov3_first.cfg weights/yolov3_900.weights prototxt/yolov3.prototxt caffemodel/yolov3.caffemodel
 Failure stack trace:unknow layer type yolo

**Comment by imzongjian** [comment]
unknow layer type yolo 
unknow layer type yolo 
save prototxt to /home/lzj/yolo2caffe/yolov3.prototxt
save caffemodel to /home/lzj/yolo2caffe/yolov3.caffemodel
-------------
请问这是没有报错的意思吗 ？我可以忽略unknow layer这句话对吗？

**Comment by ChenYingpeng** [comment]
@imzongjian Yes, good luck.
